version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./LoanControl.Presentation/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
  db:
    container_name: db
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=c86d88854a0a0d8ddf2f73d3f1f70043
      - POSTGRES_DB=LoanControl
    volumes:
      - locancontrol:/var/lib/postgresql/data

volumes:
  locancontrol:

